bushido/urls.py
from django.urls import include, path
from . import views
from bushido.views import *
from django.contrib.auth import views as auth_views
from rest_framework import routers, serializers, viewsets
from django.views.generic import TemplateView

app_name = 'bushido'


# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()
router.register(r'models', views.ModelViewSet)
router.register(r'kifeats', views.KiFeatViewSet)
router.register(r'traits', views.TraitViewSet)
router.register(r'events', views.EventViewSet)
router.register(r'enhancements', views.EnhancementViewSet)
router.register(r'themes', views.ThemeViewSet)
router.register(r'specials', views.SpecialViewSet)

urlpatterns = [
    path('', views.index, name='index'),
    path('api/', include(router.urls)),
    path('list/import/', views.import_warband, name="import_warband"),
    path('list/<str:listid>/', views.viewList, name='view_list'),
    path('list/', views.createList),
    path('list/<str:listid>/add/', views.add_to_list),
    path('list/<str:listid>/remove/', views.remove_from_list),
    path('search/', views.search, name='search'),
    path('wave/<int:wave_number>/', views.wave_list, name='wave_list'),
    path('wave/latest/', views.wave_list, name='latest_wave'),
    path('info/traits/', TraitListView.as_view(), name='allTraits'),
    path('info/traits/<int:traitid>/', views.trait_details, name='traitDetails'),
    path('info/specials/', SpecialListView.as_view(), name='allSpecials'),
    path('info/states/', StateListView.as_view(), name='allStates'),
    path('info/terms/', TermListView.as_view(), name='allTerms'),

    path('info/actions/', ActionListView.as_view(), name='allActions'),

    path('info/rulings/', RulingListView.as_view(), name='allRulings'),
    path('info/rulings/add/', views.add_ruling, name='add_ruling'),
    path('info/rulings/<int:rulingid>/edit/', views.edit_ruling, name='edit_ruling'),

    path('info/factions/', FactionListView.as_view(), name='allFactions'),
    path('info/factions/<int:factionid>/', views.faction_details, name='factionDetails'),

    path('info/feats/', FeatListView.as_view(), name='allFeats'),
    path('info/feats/add/', views.add_feat, name='add_feat'),
    path('info/feats/<int:featid>/', views.featDetails, name='featDetails'),
    path('info/feats/<int:featid>/edit/', views.editFeat, name='editFeat'),

    path('info/themes/<int:themeid>/', views.themeDetails, name='themeDetails'),
    path('info/themes/<int:themeid>/edit/', views.editTheme, name='editTheme'),

    path('info/models/', BushidoListView.as_view(), name='allModels'),
    path('info/models/add/', views.add_unit, name='add_model'),
    path('info/models/<int:unitid>/', views.unitDetails, name='modelDetails'),
    path('info/models/<int:unitid>/edit/', views.editUnit, name='editModel'),

    path('info/events/<int:eventid>/', views.eventDetails, name='eventDetails'),
    path('info/events/<int:eventid>/edit/', views.editEvent, name='editEvent'),

    path('info/enhancements/<int:enhancementid>/', views.enhancementDetails, name='enhancementDetails'),
    path('info/enhancements/<int:enhancementid>/edit/', views.editEnhancement, name='editEnhancement'),

    path('info/rules/melee-exchanges/', TemplateView.as_view(template_name="bushido/rules_views/melee_exchanges_rules.html"), name='melee_exchanges_rules'),

    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/register/', views.register, name='register'),
    path('accounts/profile/', views.userProfile, name='userProfile'),
    #path('accounts/profile/<str:username>/', views.userProfile, name='userProfile'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic.base import RedirectView

urlpatterns = [
    path("", RedirectView.as_view(pattern_name='bushido:index')),
    path("bushido/", include("bushido.urls")),
    path('admin/', admin.site.urls),
    path("__debug__/", include("debug_toolbar.urls")),
]

bushido/models.py
from django.db import models
from django.db.models import OuterRef, Subquery, Case, When, Value, Q
from django.conf import settings
from simple_history.models import HistoricalRecords
from ordered_model.models import OrderedModel
from bushido.utils import queryset_from_string, q_object_from_string, get_properties
from django_mock_queries.query import MockSet, MockModel
import shortuuid
import re
import datetime

CycleChoices = [
        ("Risen Sun", "Risen Sun"),
        ("Weeping Sky", "Weeping Sky"),
    ]


class UnitManager(models.Manager):
    def get_unique_card_names(self):
        # Fetch distinct card names along with all fields
        subquery = self.filter(cardName=OuterRef('cardName')).order_by('cardName')
        return self.filter(pk=Subquery(subquery.values('pk')[:1]))


class SpecialManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().annotate(
            type=Case(
                When(name__endswith='Attack', then=Value(1)),
                When(name__endswith='Defense', then=Value(2)),
                default=Value(3),
                output_field=models.CharField(),
            )
        ).order_by('type', 'name')


class UserProfile(models.Model):
    def __str__(self):
        return self.user.username

    ColourChoices = [
        ("light", "Light"),
        ("dark", "Dark"),
    ]

    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    website_theme = models.CharField(max_length=10, choices=ColourChoices, default="light")
    use_unofficial_cards = models.BooleanField(default=True)
    hide_unofficial_card_message = models.BooleanField(default=False)


class Faction(OrderedModel):
    def __str__(self):
        return self.name
    shortName = models.CharField(max_length=20)
    name = models.CharField(max_length=50)
    description = models.TextField()

    @property
    def all_units(self):
        return self.unit_set.all() | self.ronin_units.all()


class Unit(models.Model):

    def __str__(self):
        return self.name
    # game stuff
    name = models.CharField(max_length=50)
    cardName = models.CharField(max_length=50, default="")
    meleePool = models.CharField(max_length=3, default="0")
    meleeBoost = models.CharField(max_length=3, blank=True)
    rangedPool = models.CharField(max_length=3, default="0")
    rangedBoost = models.CharField(max_length=3, blank=True)
    movePool = models.CharField(max_length=3, default="0")
    moveBoost = models.CharField(max_length=3, blank=True)
    kiStat = models.CharField(max_length=3, default="0")
    kiBoost = models.CharField(max_length=3, blank=True)
    kiMax = models.CharField(max_length=3, default="0")
    wounds = models.CharField(max_length=3, default="5", blank=True)
    size = models.CharField(max_length=10, default="Small")
    baseSize = models.CharField(max_length=3, default="30")
    cost = models.CharField(max_length=10, default="0")
    faction = models.ForeignKey(Faction, on_delete=models.CASCADE)
    uniqueEffects = models.CharField(max_length=1500, blank=True)
    unique = models.BooleanField(default=True)
    max = models.CharField(max_length=8, default="1")

    ronin_factions = models.ManyToManyField("Faction", related_name="ronin_units", blank=True)
    kiFeats = models.ManyToManyField('KiFeat', blank=True)
    traits = models.ManyToManyField('Trait', through='UnitTrait', blank=True)

    wave = models.CharField(max_length=3, default="0")

    # internal stuff
    properties = models.CharField(max_length=1000, blank=True)

    objects = UnitManager()
    history = HistoricalRecords()

    @property
    def rulings(self):
        tags = [self.name, self.faction.name] + list(self.kiFeats.values_list("name", flat=True)) + list(self.types.values_list("type", flat=True))
        return Ruling.objects.filter(tags__tag__in=tags)

    class Meta:
        unique_together = ["faction", "name"]
        ordering = ["faction", "name"]


class KiFeat(models.Model):

    def __str__(self):
        return self.name

    TimingChoices = [
        ("Active", "Active"),
        ("Instant", "Instant"),
        ("Simple", "Simple"),
        ("Complex", "Complex"),
    ]

    TypeChoices = [
        ("Personal", "Personal"),
        ("Target", "Target"),
        ("Pulse", "Pulse"),
        ("Aura", "Aura"),
        ("Special", "Special"),
    ]

    RestrictionChoices = [
        ("OPT", "Once per Turn"),
        ("OPG", "Once per Game"),
    ]

    name = models.CharField(max_length=50)
    cost = models.CharField(max_length=6)
    timing = models.CharField(max_length=8, choices=TimingChoices, default="Active")
    featType = models.CharField(max_length=8, choices=TypeChoices, default="Personal")
    featRange = models.CharField(max_length=5, default="", blank=True)
    isOpposed = models.BooleanField(default=False)
    noMove = models.BooleanField(default=False)
    noBTB = models.BooleanField(default=False)
    limit = models.CharField(max_length=8, choices=RestrictionChoices, default="", blank=True)
    description = models.CharField(max_length=600)

    @property
    def rulings(self):
        tags = [self.name]
        return Ruling.objects.filter(tags__tag__in=tags)

    class Meta:
        ordering = ["name"]


class Trait(models.Model):

    def __str__(self):
        return self.name

    name = models.CharField(max_length=30)
    full = models.CharField(max_length=40)
    description = models.CharField(max_length=1300)

    @property
    def rulings(self):
        tags = [self.name]
        return Ruling.objects.filter(tags__tag__in=tags)

    class Meta:
        ordering = ["name"]


class Special(models.Model):
    def __str__(self):
        return self.name

    name = models.CharField(max_length=50)
    description = models.CharField(max_length=600)
    exceptional = models.BooleanField(default=False)

    objects = SpecialManager()


class UnitTrait(models.Model):

    def __str__(self):
        return self.unit.name + " - " + self.trait.name

    unit = models.ForeignKey(Unit, on_delete=models.CASCADE)
    trait = models.ForeignKey(Trait, on_delete=models.CASCADE)
    X = models.CharField(max_length=3, blank=True)
    Y = models.CharField(max_length=3, blank=True)
    descriptor = models.CharField(max_length=50, blank=True)

    @property
    def formatted(self):
        extra = self.trait.full.split(self.trait.name)[1]
        text = self.trait.name + extra\
            .replace("X", self.X)\
            .replace("Y", self.Y)\
            .replace("Descriptor", self.descriptor)\
            .replace("Bonus", self.descriptor)
        if "Descriptor" not in extra and "Bonus" not in extra and self.descriptor != "":
            text += f" [{self.descriptor}]"
        return text

    def save(self, *args, **kwargs):
        if "X" in self.trait.full and self.X == "":
            self.X = "1"
        if "Y" in self.trait.full and self.Y == "":
            self.Y = "1"
        super().save(*args, **kwargs)

    class Meta:
        ordering = ["trait__name"]


class UnitType(models.Model):

    def __str__(self):
        return self.unit.name + " - " + self.type

    unit = models.ForeignKey(Unit, related_name="types", on_delete=models.CASCADE)
    type = models.CharField(max_length=30)

    class Meta:
        ordering = ["type"]


class Event(models.Model):
    def __str__(self):
        return self.name
    name = models.CharField(max_length=50, default="")
    cycle = models.CharField(max_length=30, choices=CycleChoices, blank=True)
    cost = models.CharField(max_length=5, default="0")
    max = models.CharField(max_length=100, default="1", blank=True)
    # faction = models.CharField(max_length=15, default="")
    faction = models.ForeignKey(Faction, on_delete=models.CASCADE)
    description = models.CharField(max_length=2000, default="")
    restriction = models.CharField(max_length=300, blank=True)


class Theme(models.Model):
    def __str__(self):
        return self.faction.name + " - " + self.name
    name = models.CharField(max_length=40, default="")
    cycle = models.CharField(max_length=30, choices=CycleChoices, blank=True)
    # faction = models.CharField(max_length=15, default="")
    faction = models.ForeignKey(Faction, on_delete=models.CASCADE)
    validation = models.CharField(max_length=500, blank=True)
    description = models.CharField(max_length=1000, default="No description")
    restriction = models.CharField(max_length=300, blank=True)

    @property
    def permitted_units(self):
        permitted = Unit.objects.all()
        properties = get_properties(self)
        for filter_string in properties["FILTER"]:
            permitted = permitted.filter(q_object_from_string(filter_string))
        permitted |= Unit.objects.filter(properties__contains="ANYTHEME " + self.faction.shortName)
        # TODO models that can go in any theme that allows x model (eg niseru)
        for filter_string in properties["EXCLUDE"]:
            permitted = permitted.exclude(q_object_from_string(filter_string))
        permitted = permitted.exclude(Q(properties__contains="ONLYTHEME") & ~Q(properties__contains="ONLYTHEME " + self.name))
        return permitted.distinct()

    def save(self, *args, **kwargs):
        if len(self.validation) == 0 and len(self.restriction) != 0:
            permitted = re.search(r"Permitted \[(.*)\]", self.restriction)
            exclusion = re.search(r"Exclusion \[(.*)\]", self.restriction)
            if exclusion:
                exclusionList = exclusion.group(1).split(", ")
            if permitted:
                permittedList = permitted.group(1).split(", ")
            if permitted:
                result = "faction__shortName=\"" + self.faction.shortName + "\" AND types__type__in=["
                ronin = []
                for item in permittedList:
                    if item.find("Ronin") == -1:
                        result += "\"" + item + "\", "
                    else:

bushido/templates/bushido/base.html
<!DOCTYPE html>
<html lang="en" data-bs-theme="{% if user.is_authenticated %}{{user.userprofile.website_theme}}{% else %}light{% endif %}">
  <head>
    {% block title %}<title>Bushido Database</title>{% endblock %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta property="og:type" content="website">
    <meta property="og:site_name" content="BushidoDB">
    {% block metatags %}
    <!--meta property="og:url" content="https://bushidodb.ddns.net/bushido/"-->
    <meta property="og:title" content="BushidoDB">
    <meta property="og:description" content="Game data for Bushido, a tabletop miniature game by GCT Studios">
    <!--meta property="og:image" content=""-->
    {% endblock %}
    <!--link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous"-->
    <!-- Add additional CSS in static file -->
    {% load static %}
    <link rel="apple-touch-icon" href="{% static 'favicon.ico' %}">
    <link rel="icon" type="image/png" href="{% static 'favicon.ico' %}">
    <link href="{% static 'DataTables/datatables.min.css' %}" rel="stylesheet">
    <link href="{% static 'bushido/bushido.css' %}" rel="stylesheet">
    <script defer src="{% static 'jQuery/jquery.min.js' %}"></script>
    <script defer src="https://unpkg.com/@popperjs/core@2.11.8/dist/umd/popper.min.js"></script>
    <script defer src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
    <script defer src="{% static 'DataTables/datatables.min.js' %}"></script>
    <script defer src="{% static 'bushido/bushido.js' %}"></script>
  </head>
  <body>
    <div class="container-fluid min-vh-100 d-flex flex-column">
    {% block navbar %}
      <div class="row">
        <div class="col px-0">
          <header>
            <nav class="navbar navbar-expand-sm bg-body-tertiary">
              <div class="container">
                <div class="row flex-grow-1">
                  <div class="col-12 col-lg-2 d-flex justify-content-between">
                    <a class="navbar-brand" href="{% url 'bushido:index' %}">Bushido DB</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#main-sidebar" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                      <span class="navbar-toggler-icon"></span>
                    </button>
                  </div>
                  <div class="col-8 col-lg-4 my-1 my-lg-0">
                    <form class="d-flex" role="search" action="{% url 'bushido:search' %}">
                      <input class="form-control me-2" type="search" name="search" placeholder="Search" value="{{request.GET.search}}" aria-label="Search">
                      <button class="btn btn-outline-success" type="submit">Search</button>
                    </form>
                  </div>
                  <div class="col-4 col-lg-6 my-1 my-lg-0">
                    <div class="d-flex justify-content-end">
                      {% if user.is_authenticated %}
                      <div class="dropdown">
                        <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                          {{ user.username }}
                        </button>
                        <ul class="dropdown-menu">
                          <li><a class="dropdown-item" href="{% url 'bushido:userProfile' %}">Profile</a></li>
                          <!--li><a class="dropdown-item" href="#">Settings</a></li-->
                          <li><hr class="dropdown-divider"></li>
                          <li><a class="dropdown-item" href="{% url 'bushido:logout' %}">Log out</a></li>
                        </ul>
                      </div>
                      {% else %}
                        <a class="btn btn-secondary" href="{% url 'bushido:login' %}">Login</a>
                      {% endif %}
                    </div>
                  </div>
                </div>
              </div>
            </nav>
          </header>
        </div>
      </div>
  {% endblock %}
      <div class="row flex-grow-1">
        <div class="col-sm-2 my-0 my-md-4 border-end navbar-expand-sm collapse sidebar d-sm-block" id="main-sidebar">
        {% block sidebar %}
          <ul class="nav flex-column">
            <!--li class="nav-item"><a class="nav-link" href="{% url 'bushido:index' %}">Home</a></li-->
            <li class="nav-item"><a class="nav-link" href="{% url 'bushido:allFactions' %}">Factions</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'bushido:allModels' %}">Models</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'bushido:allFeats' %}">Ki Feats</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'bushido:allTraits' %}">Traits</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'bushido:allSpecials' %}">Special Abilities</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'bushido:allStates' %}">States</a></li>
            <hr>
            <li class="nav-item"><a class="nav-link" href="{% url 'bushido:allRulings' %}">Rulings</a></li>
          </ul>
       {% endblock %}
        </div>
        <div class="col-sm-10 py-4">
          {% if messages %}
          {% for message in messages %}
          <div class="row">
            <div class="col-lg-8 ">
              <div class="alert clearfix me-lg-4 {% if message.tags %}alert-{{ message.tags }}{% else %}alert-primary{% endif %}" role="alert">
                {{ message }}
                <button type="button" class="btn-close float-end" data-bs-dismiss="alert" aria-label="Close"></button>
              </div>
            </div>
          </div>
          {% endfor %}
          {% endif %}
          {% block content %}{% endblock %}
        </div>
      </div>
      <div class="row">
        <div class="col">
          <footer class="text-center py-1 py-md-2">
            <hr>
            <p class="fw-light">Bushido is owned by GCT Studios and content is used with permission</p>
          </footer>
        </div>
      </div>
    </div>
  </body>
</html>

bushido/templates/bushido/create_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form action="" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit">
</form>
</body>
</html>

bushido/templates/bushido/faction.html
{% extends "bushido/base.html" %}
{% load static %}
{% block title %}<title>{{faction.name}} - Info</title>{% endblock %}
{% block content %}
<div class="container m-0">
    <div>
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'bushido:index' %}">Home</a></li>
        <li class="breadcrumb-item"><a href="{% url 'bushido:allFactions' %}">Factions</a></li>
        <li class="breadcrumb-item active" aria-current="page">Faction</a></li>
      </ol>
    </nav>
  </div>
    <div class="row">
        <h2>{{faction.name}}</h2>
    </div>
  <hr>
    <div class="row">
<p>{{faction.description|linebreaks}}</p>
    </div>
  <hr>
    <div class="row">
<h4>Faction models:</h4>
<ul class="list-group">
    {% for unit in faction.unit_set.all %}
    <a class="list-group-item list-group-item-action" href="{% url 'bushido:modelDetails' unitid=unit.id%}">{{ unit.name }}</a>
        {% endfor %}
</ul>
    </div>
    <hr>
    <div class="row">
<h4>Faction Themes:</h4>
<ul class="list-group">
{% for theme in faction.theme_set.all %}
<a class="list-group-item list-group-item-action" href="{% url 'bushido:themeDetails' themeid=theme.id%}">{{ theme.name }}</a>
    {% endfor %}
    </ul>
    </div>
    <hr>
    <div class="row">
<h4>Faction Events:</h4>
<ul class="list-group">
{% for event in faction.event_set.all %}
<a class="list-group-item list-group-item-action" href="{% url 'bushido:eventDetails' eventid=event.id%}">{{ event.name }}</a>
    {% endfor %}
        </ul>
    </div>
  <hr>
      <div class="row">
<h4>Faction Enhancements:</h4>
<ul class="list-group">
  {% for enhancement in faction.enhancement_set.all %}
  {% if not enhancement.isEquipment %}
<a class="list-group-item list-group-item-action" href="{% url 'bushido:enhancementDetails' enhancementid=enhancement.id%}">{{ enhancement.name }}</a>
   {% endif %}
    {% endfor %}
        </ul>
    </div>
  <hr>
      <div class="row">
<h4>Faction Equipment:</h4>
<ul class="list-group">
  {% for enhancement in faction.enhancement_set.all %}
  {% if enhancement.isEquipment %}
<a class="list-group-item list-group-item-action" href="{% url 'bushido:enhancementDetails' enhancementid=enhancement.id%}">{{ enhancement.name }}</a>
  {% endif %}
    {% endfor %}
        </ul>
    </div>
  {% if faction.name != "Ronin" %}
  <hr>
      <div>

<h4>Ronin models:</h4>
<ul class="list-group">
    {% for unit in faction.ronin_units.all %}
    <a class="list-group-item list-group-item-action" href="{% url 'bushido:modelDetails' unitid=unit.id%}">{{ unit.name }}</a>
        {% endfor %}
</ul>
    </div>
  {% endif %}
</div>
{% endblock %}

bushido/templates/bushido/import_warband.html
{% extends "bushido/base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}<title>Import Warband</title>{% endblock %}
{% block metatags %}
    <meta property="og:title" content="Import Warband">
    <meta property="og:site_name" content="BushidoDB">
    <meta property="og:description" content="Import">
{% endblock %}
{% block content %}
<div class="container m-0">
    <h1>Import Warband</h1>
    <form method="post" action="{% url 'bushido:import_warband' %}">
        {% csrf_token %}
        {{ form|crispy }}
        <input class="btn btn-outline-secondary" type="submit" value="Submit">
  </form>
</div>
{% endblock %}s

bushido/templates/bushido/index.html
{% extends "bushido/base.html" %}
{% block title %}<title>Bushido Database</title>{% endblock %}
{% block content %}
<div class="container-fluid">
  <h1>Welcome
    {% if user.is_authenticated %}
    - {{ user.username }}
    {% endif %}
  </h1>
  <p>Eventually there may be some content here, but for now use the links on the left</p>
</div>
{% endblock %}

bushido/templates/bushido/theme_details.html
{% extends "bushido/base.html" %}
{% load static %}
{% block title %}<title>{{theme.name}} - Info</title>{% endblock %}
{% block metatags %}
<meta property="og:title" content="{{theme.name}} - BushidoDB">
<meta property="og:image" content="{% static card %}">
<meta name="twitter:card" content="summary_large_image">
{% endblock %}
{% block content %}
<div class="container m-0">
  <div>
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'bushido:index' %}">Home</a></li>
        <li class="breadcrumb-item"><a href="{% url 'bushido:allFactions' %}">Factions</a></li>
        <li class="breadcrumb-item"><a href="{% url 'bushido:factionDetails' factionid=theme.faction.id%}">{{theme.faction.name}}</a></li>
        <li class="breadcrumb-item active" aria-current="page">Theme</li>
      </ol>
    </nav>
  </div>
  <div class="row">
    <h2 class="pb-0">{{theme.name}}</h2>
    {% if theme.cycle != "" %}
    <p class="fw-light">{{theme.cycle}}</p>
    {% endif %}
  </div>
  <hr>
    <div class="container single-card-container ms-md-4 text-center">
      <img src="{% static card %}" class="img-fluid d-block" alt = "{{theme.name}}">
      {% if not user.userprofile.hide_unofficial_card_message and "/unofficial/" in card  %}
      <p class="fw-light">Unofficial Card</p>
      {% endif %}
    </div>
  <hr>
    <div class="row">
      <h4>Description:</h4>
      <p>{{theme.description|linebreaksbr}}</p>
      {% if theme.restriction != "" %}<p>{{theme.restriction|linebreaksbr}}</p>{% endif %}
    </div>
  <hr>
    <div class="row">
<h4>Permitted Models:</h4>
        <ul class="list-group">
{% for unit in permitted %}
<a class="list-group-item list-group-item-action" href="{% url 'bushido:modelDetails' unitid=unit.id%}">{{ unit.name }}</a>
    {% endfor %}
        </ul>
    </div>
  {% if perms.bushido.change_theme %}
  <hr>
  <a class="btn btn-outline-secondary" href="./edit/" role="button">Edit theme</a>
  {% endif %}
</div>
{% endblock %}

bushido/templates/bushido/user_profile.html
{% extends "bushido/base.html" %}
{% block title %}<title>{{user.username}}</title>{% endblock %}
{% block content %}
{% load crispy_forms_tags %}
<div class="container m-0">
  <div class="row">
    <div class="col-lg-6">
      <h2>Profile</h2>
      <div>
        <h4>Settings</h4>
        <form method="post" action="{% url 'bushido:userProfile' %}">
          {% csrf_token %}
          {{ form|crispy }}
          <input class="btn btn-outline-secondary" type="submit" value="Submit">
        </form>
      </div>
    </div>
  </div>
  {% for list in lists %}
    <a href="#">{{list.name}}</a>
  {% endfor %}
</div>
{% endblock %}