bushido/urls.py
from django.urls import include, path
from . import views
from bushido.views import *
from django.contrib.auth import views as auth_views
from rest_framework import routers, serializers, viewsets
from django.views.generic import TemplateView

app_name = 'bushido'


# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()
router.register(r'models', views.ModelViewSet)
router.register(r'kifeats', views.KiFeatViewSet)
router.register(r'traits', views.TraitViewSet)
router.register(r'events', views.EventViewSet)
router.register(r'enhancements', views.EnhancementViewSet)
router.register(r'themes', views.ThemeViewSet)
router.register(r'specials', views.SpecialViewSet)

urlpatterns = [
    path('', views.index, name='index'),
    path('api/', include(router.urls)),
    path('list/import/', views.import_warband, name="import_warband"),
    path('list/<str:listid>/', views.viewList, name='view_list'),
    path('list/', views.createList),
    path('list/<str:listid>/add/', views.add_to_list),
    path('list/<str:listid>/remove/', views.remove_from_list),
    path('search/', views.search, name='search'),
    path('wave/<int:wave_number>/', views.wave_list, name='wave_list'),
    path('wave/latest/', views.wave_list, name='latest_wave'),
    path('info/traits/', TraitListView.as_view(), name='allTraits'),
    path('info/traits/<int:traitid>/', views.trait_details, name='traitDetails'),
    path('info/specials/', SpecialListView.as_view(), name='allSpecials'),
    path('info/states/', StateListView.as_view(), name='allStates'),
    path('info/terms/', TermListView.as_view(), name='allTerms'),

    path('info/actions/', ActionListView.as_view(), name='allActions'),

    path('info/rulings/', RulingListView.as_view(), name='allRulings'),
    path('info/rulings/add/', views.add_ruling, name='add_ruling'),
    path('info/rulings/<int:rulingid>/edit/', views.edit_ruling, name='edit_ruling'),

    path('info/factions/', FactionListView.as_view(), name='allFactions'),
    path('info/factions/<int:factionid>/', views.faction_details, name='factionDetails'),

    path('info/feats/', FeatListView.as_view(), name='allFeats'),
    path('info/feats/add/', views.add_feat, name='add_feat'),
    path('info/feats/<int:featid>/', views.featDetails, name='featDetails'),
    path('info/feats/<int:featid>/edit/', views.editFeat, name='editFeat'),

    path('info/themes/<int:themeid>/', views.themeDetails, name='themeDetails'),
    path('info/themes/<int:themeid>/edit/', views.editTheme, name='editTheme'),

    path('info/models/', BushidoListView.as_view(), name='allModels'),
    path('info/models/add/', views.add_unit, name='add_model'),
    path('info/models/<int:unitid>/', views.unitDetails, name='modelDetails'),
    path('info/models/<int:unitid>/edit/', views.editUnit, name='editModel'),

    path('info/events/<int:eventid>/', views.eventDetails, name='eventDetails'),
    path('info/events/<int:eventid>/edit/', views.editEvent, name='editEvent'),

    path('info/enhancements/<int:enhancementid>/', views.enhancementDetails, name='enhancementDetails'),
    path('info/enhancements/<int:enhancementid>/edit/', views.editEnhancement, name='editEnhancement'),

    path('info/rules/melee-exchanges/', TemplateView.as_view(template_name="bushido/rules_views/melee_exchanges_rules.html"), name='melee_exchanges_rules'),

    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/register/', views.register, name='register'),
    path('accounts/profile/', views.userProfile, name='userProfile'),
    #path('accounts/profile/<str:username>/', views.userProfile, name='userProfile'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic.base import RedirectView

urlpatterns = [
    path("", RedirectView.as_view(pattern_name='bushido:index')),
    path("bushido/", include("bushido.urls")),
    path('admin/', admin.site.urls),
    path("__debug__/", include("debug_toolbar.urls")),
]

bushido/views.py
from django.shortcuts import render, redirect, get_object_or_404, reverse
from django.http import HttpResponse, HttpResponseNotFound, HttpResponseRedirect
from django.views.generic import ListView
from bushido.models import Unit, KiFeat, UnitTrait, Trait, Theme, Event, List, ListUnit, Weapon, UserProfile,\
    WeaponTrait, WeaponSpecial, Faction, Special, Enhancement
from django.db.models import Q, Prefetch, Max
from django.db import models
from django.contrib import auth, messages
from .forms import *
from django.contrib.auth.decorators import permission_required
from django.contrib.auth import login
from rest_framework import viewsets
from bushido.serializers import *
from bushido.utils import queryset_from_string, get_card, text_to_list
from bushido.search import search_all
import jellyfish


MESSAGE_TAGS = {
    messages.DEBUG: "primary",
    messages.ERROR: "danger",
}


class ModelViewSet(viewsets.ReadOnlyModelViewSet):
    """
    Retrieve model information
    """
    queryset = Unit.objects.prefetch_related('kiFeats', 'traits', 'ronin_factions', 'unittrait_set__trait', 'types',
                                             "weapons__weaponspecials__special", "weapons__weapontraits__trait").select_related('faction')
    serializer_class = UnitSerializer
    permission_classes = []
    filterset_fields = "__all__"


class KiFeatViewSet(viewsets.ReadOnlyModelViewSet):
    """
    Retrieve ki feat information
    """
    queryset = KiFeat.objects.all()
    serializer_class = KiFeatSerializer
    permission_classes = []
    filterset_fields = "__all__"


class TraitViewSet(viewsets.ReadOnlyModelViewSet):
    """
    Retrieve trait information
    """
    queryset = Trait.objects.all()
    serializer_class = TraitSerializer
    permission_classes = []
    filterset_fields = "__all__"


class EventViewSet(viewsets.ReadOnlyModelViewSet):
    """
    Retrieve event information
    """
    queryset = Event.objects.prefetch_related("faction")
    serializer_class = EventSerializer
    permission_classes = []
    filterset_fields = "__all__"


class EnhancementViewSet(viewsets.ReadOnlyModelViewSet):
    """
    Retrieve enhancement information
    """
    queryset = Enhancement.objects.prefetch_related("faction")
    serializer_class = EnhancementSerializer
    permission_classes = []
    filterset_fields = "__all__"


class ThemeViewSet(viewsets.ReadOnlyModelViewSet):
    """
    Retrieve theme information
    """
    queryset = Theme.objects.prefetch_related("faction")
    serializer_class = ThemeSerializer
    permission_classes = []
    filterset_fields = "__all__"


class SpecialViewSet(viewsets.ReadOnlyModelViewSet):
    """
    Retrieve special ability information
    """
    queryset = Special.objects.all()
    serializer_class = SpecialSerializer
    permission_classes = []
    filterset_fields = "__all__"


def index(request):
    return render(request, 'bushido/index.html')


def register(request):
    form = RegisterForm()

    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('/bushido/')
        else:
            return render(request, 'registration/register.html', {'registerForm': form})
    return render(request, 'registration/register.html', {"registerForm": form})


def search(request):
    search_query = request.GET["search"]
    result = search_all(search_query)
    if len(result) == 1:
        if result[0].name.lower() == search_query.lower():
            model = result[0]
            classNames = {
                "Unit": "Model",
                "KiFeat": "Feat"
            }
            return redirect('/bushido/info/{}s/{}/'.format(
                classNames.get(model.__class__.__name__, model.__class__.__name__).lower(), model.pk))
    return render(request, 'bushido/search.html', {"search_results": result})


def wave_list(request, wave_number=None):
    if wave_number is None:
        wave_number = str(Unit.objects.aggregate(Max('wave')).get('wave__max'))
    print(wave_number)
    wave_units = Unit.objects.get_unique_card_names().filter(wave=wave_number).prefetch_related("faction")
    return render(request, 'bushido/list_views/unit_wave.html', {'wave_number': wave_number, "wave_units": wave_units})


def featDetails(request, featid):
    feat = get_object_or_404(KiFeat, pk=featid)
    return render(request, 'bushido/detail_views/feat_details.html', {'feat': feat})


@permission_required("bushido.change_ki_feat")
def editFeat(request, featid):
    feat = get_object_or_404(KiFeat, pk=featid)
    if request.method == "POST":
        form = EditFeat(request.POST, instance=feat)
        if form.is_valid():
            form.save()
            return redirect(reverse('bushido:featDetails', kwargs={'featid': featid}))
    else:
        form = EditFeat(instance=feat)
    return render(request, 'bushido/edit_views/edit_feat.html', {'feat': feat, "form": form})


@permission_required("bushido.add_ki_feat")
def add_feat(request):
    if request.method == "POST":
        form = EditFeat(request.POST)
        if form.is_valid():
            feat = form.save()
            return redirect(reverse('bushido:featDetails', kwargs={'featid': feat.id}))
    else:
        form = EditFeat()
    return render(request, 'bushido/edit_views/edit_feat.html', {"form": form})


def unitDetails(request, unitid):
    unit = get_object_or_404(
        Unit.objects.prefetch_related(
            Prefetch('unittrait_set', queryset=UnitTrait.objects.select_related('trait')),
            Prefetch('weapons', queryset=Weapon.objects.prefetch_related('weaponspecials__special', 'weapontraits__trait')),
        ),
        pk=unitid
    )
    cardUnits = Unit.objects.filter(cardName=unit.cardName)
    cardFront = get_card(request.user, unit, " Front")
    cardBack = get_card(request.user, unit, " Reverse")

    return render(request, 'bushido/detail_views/unit_details.html',
                  {'unit': unit, 'cardUnits': cardUnits, 'cardFront': cardFront, 'cardBack': cardBack})


@permission_required("bushido.change_unit")
def editUnit(request, unitid):
    unit = get_object_or_404(Unit, pk=unitid)
    cardFront = get_card(request.user, unit, " Front")
    cardBack = get_card(request.user, unit, " Reverse")

    if request.method == "POST":
        unitForm = EditUnit(request.POST, instance=unit)
        typeForm = TypeFormSet(request.POST, instance=unit, prefix="types")
        traitForm = TraitFormSet(request.POST, instance=unit, prefix="traits")
        weapon_formset = WeaponFormSet(request.POST, instance=unit, queryset=Weapon.objects.filter(unit=unit))
        if unitForm.is_valid() and weapon_formset.is_valid() and traitForm.is_valid() and typeForm.is_valid():
            unitForm.save()
            weapon_formset.save()
            traitForm.save()
            typeForm.save()
            return redirect(reverse('bushido:modelDetails', kwargs={'unitid': unitid}))

    else:
        unitForm = EditUnit(instance=unit)
        typeForm = TypeFormSet(instance=unit, prefix="types")
        traitForm = TraitFormSet(instance=unit, prefix="traits")
        weapon_formset = WeaponFormSet(instance=unit, queryset=Weapon.objects.filter(unit=unit), prefix="weapons")
    return render(request, 'bushido/edit_views/edit_unit.html',
                  {'unit': unit, 'cardFront': cardFront, 'cardBack': cardBack,
                   "form": unitForm, 'weapon_formset': weapon_formset, 'trait_form': traitForm, 'type_form': typeForm})


@permission_required("bushido.add_unit")
def add_unit(request):
    if request.method == "POST":
        form = AddUnit(request.POST)
        if form.is_valid():
            unit = form.save()
            return redirect(reverse('bushido:editModel', kwargs={'unitid': unit.id}))
    else:
        form = AddUnit()
    return render(request, 'bushido/edit_views/add_unit.html', {"form": form})


def trait_details(request, traitid):
    trait = get_object_or_404(Trait, pk=traitid)
    units = Unit.objects.filter(Q(traits=trait) | Q(weapons__traits=trait)).distinct()
    feats = KiFeat.objects.filter(description__icontains=trait.name)
    return render(request, 'bushido/detail_views/trait_details.html', {'trait': trait, 'units': units, 'feats': feats})


@permission_required("bushido.add_ruling")
def add_ruling(request):
    if request.method == "POST":
        ruling_form = AddRuling(request.POST)
        tag_form = RulingTagFormSet(request.POST, instance=ruling_form.instance, prefix="tags")
        if ruling_form.is_valid() and tag_form.is_valid():
            ruling = ruling_form.save()
            tag_form.save()
            return redirect(reverse('bushido:allRulings'))
    else:
        ruling_form = AddRuling()
        tag_form = RulingTagFormSet(prefix="tags")
    return render(request, 'bushido/edit_views/add_ruling.html', {"form": ruling_form, "tag_form": tag_form})


@permission_required("bushido.change_ruling")
def edit_ruling(request, rulingid):
    ruling = get_object_or_404(Ruling, pk=rulingid)
    if request.method == "POST":
        ruling_form = AddRuling(request.POST, instance=ruling)
        tag_form = RulingTagFormSet(request.POST, instance=ruling, prefix="tags")
        if ruling_form.is_valid() and tag_form.is_valid():
            ruling_form.save()
            tag_form.save()
            return redirect(reverse('bushido:allRulings'))
    else:
        ruling_form = AddRuling(instance=ruling)
        tag_form = RulingTagFormSet(instance=ruling, prefix="tags")
    return render(request, 'bushido/edit_views/add_ruling.html', {"form": ruling_form, "tag_form": tag_form})


def themeDetails(request, themeid):
    theme = get_object_or_404(Theme, pk=themeid)
    card = get_card(request.user, theme)
    return render(request, 'bushido/detail_views/theme_details.html', {'theme': theme, 'card': card})


@permission_required("bushido.change_theme")

bushido/templates/bushido/list_views/action_list.html
{% extends "bushido/base.html" %}
{% block title %}<title>Actions</title>{% endblock %}
{% block content %}
<div class="container m-0">
    <h2>Actions</h2>
    <table class="table table-striped table-hover">
        <thead>
            <tr>
                <th>Name</th>
                <th>Type</th>
                <th>Description</th>
            </tr>
        </thead>
        <tbody>
            {% for action in action_list %}
                <tr id="{{ action.name }}">
                    <td><span>{{ action.name }}</span></td>
                    <td>{{ action.action_type }}</td>
                    <td>{{ action.description }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

bushido/templates/bushido/list_views/faction_list.html
{% extends "bushido/base.html" %}
{% block title %}<title>Factions</title>{% endblock %}
{% block metatags %}
    <meta property="og:title" content="Factions">
    <meta property="og:description" content="View the list of Bushido factions">
{% endblock %}
{% block content %}
<div class="container m-0">
    <div>
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'bushido:index' %}">Home</a></li>
        <li class="breadcrumb-item active" aria-current="page">Factions</a></li>
      </ol>
    </nav>
  </div>
    <div class="row">
        <h2>Factions</h2>
    </div>
    <div class="row">
        <ul class="list-group">
        {% for faction in faction_list %}
            <a class="list-group-item list-group-item-action" href="{% url 'bushido:factionDetails' factionid=faction.id %}">
                {{faction.name}}
            </a>
        {% endfor %}
        </ul>
    </div>
</div>
{% endblock %}

bushido/templates/bushido/list_views/kifeat_list.html
{% extends "bushido/base.html" %}
{% block title %}<title>All Ki Feats</title>{% endblock %}
{% block content %}
<div class="container m-0">
    <h2>All Ki Feats</h2>
    {% if perms.bushido.add_ki_feat %}
      <a class="btn btn-outline-secondary" href="{% url 'bushido:add_feat' %}" role="button">Add New</a>
    {% endif %}
    <table class="table table-striped table-hover">
        <thead>
            <tr>
                <th>Name</th>
                <th>Cost</th>
                <th>Timing</th>
                <th>Type</th>
            </tr>
        </thead>
        <tbody>
            {% for feat in kifeat_list %}
                <tr>
                    <td><a href="{% url 'bushido:featDetails' featid=feat.id%}">{{ feat.name }}</a></td>
                    <td>{{ feat.cost }}</td>
                    <td>{{ feat.timing }}</td>
                    <td>{{ feat.featType }}</td>
                    <td>{{ feat.description }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

bushido/templates/bushido/list_views/ruling_list.html
{% extends "bushido/base.html" %}
{% block title %}<title>Rulings</title>{% endblock %}
{% block content %}
<div class="container m-0">
    <h2>Rulings</h2>
  {% if perms.bushido.add_ruling %}
    <a class="btn btn-outline-secondary mb-3" href="{% url 'bushido:add_ruling' %}" role="button">Add New</a>
  {% endif %}
    <div class="list-group">
      {% for ruling in ruling_list %}
      <div class="list-group-item w-auto py-md-2">
        <div class="container-fluid p-0">
          <div class="row pe-2">
            <div class="pe-0 {% if perms.bushido.change_ruling %}col-12 col-md-10 col-lg-11{% endif %}">
              <p id="{{ruling.pk}}" class="highlighter"><span class="highlight">{{ ruling.ruling }}</span></p>
            </div>
            {% if perms.bushido.change_ruling %}
            <div class="col-12 col-md-2 col-lg-1 pe-0">
              <a class="btn btn-outline-secondary float-md-end" href="./{{ruling.pk}}/edit/" role="button">Edit</a>
            </div>
            {% endif %}
          </div>
        </div>
        <div class="d-flex">
          <small class="me-auto">
            {% for tag in ruling.tags.all %}
              {{ tag.tag }}{% if not forloop.last %}, {% endif %}
            {% endfor %}
          </small>
          <small><a href="" class="copy-link text-reset" data-copy-link="{% url 'bushido:allRulings' %}#{{ruling.pk}}"
        data-bs-toggle="tooltip" data-bs-placement="top" data-bs-trigger="manual" data-bs-title="Copied link!">{{ ruling.date }}</a></small>
        </div>
      </div>
      {% endfor %}
    </div>
</div>
{% endblock %}

bushido/templates/bushido/list_views/special_list.html
{% extends "bushido/base.html" %}
{% block title %}<title>Special Abilities</title>{% endblock %}
{% block content %}
<div class="container m-0">
    <h2>Special Abilities</h2>
    <table class="table table-striped table-hover">
        <thead>
            <tr>
                <th>Name</th>
                <th>Description</th>
            </tr>
        </thead>
        <tbody>
            {% for special in special_list %}
                <tr id="{{ special.name }}">
                    <td><span>{{ special.name }}</span></td>
                    <td>{{ special.description }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

bushido/templates/bushido/list_views/state_list.html
{% extends "bushido/base.html" %}
{% block title %}<title>States</title>{% endblock %}
{% block content %}
<div class="container m-0">
    <h2>States</h2>
    <table class="table table-striped table-hover">
        <thead>
            <tr>
                <th>Name</th>
                <th>Description</th>
            </tr>
        </thead>
        <tbody>
            {% for state in state_list %}
                <tr id="{{ state.name }}">
                    <td><span>{{ state.name }}</span></td>
                    <td>{{ state.description }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

bushido/templates/bushido/list_views/term_list.html
{% extends "bushido/base.html" %}
{% block title %}<title>Terms and Concepts</title>{% endblock %}
{% block content %}
<div class="container m-0">
    <h2>Terms and Concepts</h2>
    <table class="table table-striped table-hover">
        <thead>
            <tr>
                <th>Name</th>
                <th>Description</th>
            </tr>
        </thead>
        <tbody>
            {% for term in term_list %}
                <tr id="{{ term.name }}">
                    <td><span>{{ term.name }}</span></td>
                    <td>{{ term.description }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

bushido/templates/bushido/list_views/trait_list.html
{% extends "bushido/base.html" %}
{% block title %}<title>All Traits</title>{% endblock %}
{% block content %}
<div class="container m-0">
    <h2>All Traits</h2>
    <table class="table table-striped table-hover">
        <thead>
            <tr>
                <th>Name</th>
                <th>Description</th>
            </tr>
        </thead>
        <tbody>
            {% for trait in trait_list %}
                <tr id="{{ trait.name }}">
                    <td><span><a href="{% url 'bushido:traitDetails' traitid=trait.id%}">{{ trait.name }}</a></span></td>
                    <td>{{ trait.description }}</td>
                </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

bushido/templates/bushido/list_views/unit_list.html
{% extends "bushido/base.html" %}
{% block title %}<title>All Models</title>{% endblock %}
{% load bushidofilters %}
{% block content %}
<div class="container-fluid pe-1">
  <div class="row">
    <h2>All Models</h2>
  </div>
  {% if perms.bushido.add_unit %}
    <a class="btn btn-outline-secondary" href="{% url 'bushido:add_model' %}" role="button">Add New</a>
  {% endif %}
  <div class="row">
    <div class="col-lg-9">
      <table id="modelTable" class="table table-striped table-hover data-table">
        <thead>
        <tr>
          <th>Name</th>
          <th>Melee</th>
          <th>Ranged</th>
          <th>Ki</th>
          <th>Move</th>
          <th>Wounds</th>
          <th>Cost</th>
          <th>Faction</th>
        </tr>
        </thead>
        <tbody>
        {% for unit in unit_list %}
        <tr>
          <td><a href="{% url 'bushido:modelDetails' unitid=unit.id%}">{{ unit.name }}</a></td>
          <td>{{unit.meleePool}} {{unit.meleeBoost|addBrackets}}</td>
          <td>{{unit.rangedPool}} {{unit.rangedBoost|addBrackets}}</td>
          <td>{{unit.kiStat}}/{{unit.kiMax}} {{unit.kiBoost|addBrackets}}</td>
          <td>{{unit.movePool}} {{unit.moveBoost|addBrackets}}</td>
          <td>{{unit.wounds}}</td>
          <td>{{unit.cost}}</td>
          <td>{{unit.faction.name}}</td>
        </tr>
        {% endfor %}
        </tbody>
      </table>
    </div>
    <div class="col-lg-3">
      <div class="search-panes" id="searchPanesContainer">

      </div>
    </div>
  </div>
</div>
{% endblock %}

bushido/templates/bushido/list_views/unit_wave.html
{% extends "bushido/base.html" %}
{% block title %}<title>Wave {{ wave_number }}</title>{% endblock %}
{% block metatags %}
    <meta property="og:title" content="Wave {{ wave_number }}">
    <meta property="og:description" content="View the list of models released in wave {{ wave_number }}">
{% endblock %}
{% block content %}
<div class="container m-0">
  <h1>Wave {{ wave_number }}</h1>
  <div>
    <ul class="list-group">
      {% for unit in wave_units %}
            <a class="list-group-item list-group-item-action" href="{% url 'bushido:modelDetails' unitid=unit.id %}">
                {{unit.cardName}} - {{unit.faction.name}}
            </a>
        {% endfor %}
    <ul>
  </div>
</div>
{% endblock %}