bushido/urls.py
from django.urls import include, path
from . import views
from bushido.views import *
from django.contrib.auth import views as auth_views
from rest_framework import routers, serializers, viewsets
from django.views.generic import TemplateView

app_name = 'bushido'


# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()
router.register(r'models', views.ModelViewSet)
router.register(r'kifeats', views.KiFeatViewSet)
router.register(r'traits', views.TraitViewSet)
router.register(r'events', views.EventViewSet)
router.register(r'enhancements', views.EnhancementViewSet)
router.register(r'themes', views.ThemeViewSet)
router.register(r'specials', views.SpecialViewSet)

urlpatterns = [
    path('', views.index, name='index'),
    path('api/', include(router.urls)),
    path('list/import/', views.import_warband, name="import_warband"),
    path('list/<str:listid>/', views.viewList, name='view_list'),
    path('list/', views.createList),
    path('list/<str:listid>/add/', views.add_to_list),
    path('list/<str:listid>/remove/', views.remove_from_list),
    path('search/', views.search, name='search'),
    path('wave/<int:wave_number>/', views.wave_list, name='wave_list'),
    path('wave/latest/', views.wave_list, name='latest_wave'),
    path('info/traits/', TraitListView.as_view(), name='allTraits'),
    path('info/traits/<int:traitid>/', views.trait_details, name='traitDetails'),
    path('info/specials/', SpecialListView.as_view(), name='allSpecials'),
    path('info/states/', StateListView.as_view(), name='allStates'),
    path('info/terms/', TermListView.as_view(), name='allTerms'),

    path('info/actions/', ActionListView.as_view(), name='allActions'),

    path('info/rulings/', RulingListView.as_view(), name='allRulings'),
    path('info/rulings/add/', views.add_ruling, name='add_ruling'),
    path('info/rulings/<int:rulingid>/edit/', views.edit_ruling, name='edit_ruling'),

    path('info/factions/', FactionListView.as_view(), name='allFactions'),
    path('info/factions/<int:factionid>/', views.faction_details, name='factionDetails'),

    path('info/feats/', FeatListView.as_view(), name='allFeats'),
    path('info/feats/add/', views.add_feat, name='add_feat'),
    path('info/feats/<int:featid>/', views.featDetails, name='featDetails'),
    path('info/feats/<int:featid>/edit/', views.editFeat, name='editFeat'),

    path('info/themes/<int:themeid>/', views.themeDetails, name='themeDetails'),
    path('info/themes/<int:themeid>/edit/', views.editTheme, name='editTheme'),

    path('info/models/', BushidoListView.as_view(), name='allModels'),
    path('info/models/add/', views.add_unit, name='add_model'),
    path('info/models/<int:unitid>/', views.unitDetails, name='modelDetails'),
    path('info/models/<int:unitid>/edit/', views.editUnit, name='editModel'),

    path('info/events/<int:eventid>/', views.eventDetails, name='eventDetails'),
    path('info/events/<int:eventid>/edit/', views.editEvent, name='editEvent'),

    path('info/enhancements/<int:enhancementid>/', views.enhancementDetails, name='enhancementDetails'),
    path('info/enhancements/<int:enhancementid>/edit/', views.editEnhancement, name='editEnhancement'),

    path('info/rules/melee-exchanges/', TemplateView.as_view(template_name="bushido/rules_views/melee_exchanges_rules.html"), name='melee_exchanges_rules'),

    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/register/', views.register, name='register'),
    path('accounts/profile/', views.userProfile, name='userProfile'),
    #path('accounts/profile/<str:username>/', views.userProfile, name='userProfile'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic.base import RedirectView

urlpatterns = [
    path("", RedirectView.as_view(pattern_name='bushido:index')),
    path("bushido/", include("bushido.urls")),
    path('admin/', admin.site.urls),
    path("__debug__/", include("debug_toolbar.urls")),
]

bushido/models.py
from django.db import models
from django.db.models import OuterRef, Subquery, Case, When, Value, Q
from django.conf import settings
from simple_history.models import HistoricalRecords
from ordered_model.models import OrderedModel
from bushido.utils import queryset_from_string, q_object_from_string, get_properties
from django_mock_queries.query import MockSet, MockModel
import shortuuid
import re
import datetime

CycleChoices = [
        ("Risen Sun", "Risen Sun"),
        ("Weeping Sky", "Weeping Sky"),
    ]


class UnitManager(models.Manager):
    def get_unique_card_names(self):
        # Fetch distinct card names along with all fields
        subquery = self.filter(cardName=OuterRef('cardName')).order_by('cardName')
        return self.filter(pk=Subquery(subquery.values('pk')[:1]))


class SpecialManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().annotate(
            type=Case(
                When(name__endswith='Attack', then=Value(1)),
                When(name__endswith='Defense', then=Value(2)),
                default=Value(3),
                output_field=models.CharField(),
            )
        ).order_by('type', 'name')


class UserProfile(models.Model):
    def __str__(self):
        return self.user.username

    ColourChoices = [
        ("light", "Light"),
        ("dark", "Dark"),
    ]

    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    website_theme = models.CharField(max_length=10, choices=ColourChoices, default="light")
    use_unofficial_cards = models.BooleanField(default=True)
    hide_unofficial_card_message = models.BooleanField(default=False)


class Faction(OrderedModel):
    def __str__(self):
        return self.name
    shortName = models.CharField(max_length=20)
    name = models.CharField(max_length=50)
    description = models.TextField()

    @property
    def all_units(self):
        return self.unit_set.all() | self.ronin_units.all()


class Unit(models.Model):

    def __str__(self):
        return self.name
    # game stuff
    name = models.CharField(max_length=50)
    cardName = models.CharField(max_length=50, default="")
    meleePool = models.CharField(max_length=3, default="0")
    meleeBoost = models.CharField(max_length=3, blank=True)
    rangedPool = models.CharField(max_length=3, default="0")
    rangedBoost = models.CharField(max_length=3, blank=True)
    movePool = models.CharField(max_length=3, default="0")
    moveBoost = models.CharField(max_length=3, blank=True)
    kiStat = models.CharField(max_length=3, default="0")
    kiBoost = models.CharField(max_length=3, blank=True)
    kiMax = models.CharField(max_length=3, default="0")
    wounds = models.CharField(max_length=3, default="5", blank=True)
    size = models.CharField(max_length=10, default="Small")
    baseSize = models.CharField(max_length=3, default="30")
    cost = models.CharField(max_length=10, default="0")
    faction = models.ForeignKey(Faction, on_delete=models.CASCADE)
    uniqueEffects = models.CharField(max_length=1500, blank=True)
    unique = models.BooleanField(default=True)
    max = models.CharField(max_length=8, default="1")

    ronin_factions = models.ManyToManyField("Faction", related_name="ronin_units", blank=True)
    kiFeats = models.ManyToManyField('KiFeat', blank=True)
    traits = models.ManyToManyField('Trait', through='UnitTrait', blank=True)

    wave = models.CharField(max_length=3, default="0")

    # internal stuff
    properties = models.CharField(max_length=1000, blank=True)

    objects = UnitManager()
    history = HistoricalRecords()

    @property
    def rulings(self):
        tags = [self.name, self.faction.name] + list(self.kiFeats.values_list("name", flat=True)) + list(self.types.values_list("type", flat=True))
        return Ruling.objects.filter(tags__tag__in=tags)

    class Meta:
        unique_together = ["faction", "name"]
        ordering = ["faction", "name"]


class KiFeat(models.Model):

    def __str__(self):
        return self.name

    TimingChoices = [
        ("Active", "Active"),
        ("Instant", "Instant"),
        ("Simple", "Simple"),
        ("Complex", "Complex"),
    ]

    TypeChoices = [
        ("Personal", "Personal"),
        ("Target", "Target"),
        ("Pulse", "Pulse"),
        ("Aura", "Aura"),
        ("Special", "Special"),
    ]

    RestrictionChoices = [
        ("OPT", "Once per Turn"),
        ("OPG", "Once per Game"),
    ]

    name = models.CharField(max_length=50)
    cost = models.CharField(max_length=6)
    timing = models.CharField(max_length=8, choices=TimingChoices, default="Active")
    featType = models.CharField(max_length=8, choices=TypeChoices, default="Personal")
    featRange = models.CharField(max_length=5, default="", blank=True)
    isOpposed = models.BooleanField(default=False)
    noMove = models.BooleanField(default=False)
    noBTB = models.BooleanField(default=False)
    limit = models.CharField(max_length=8, choices=RestrictionChoices, default="", blank=True)
    description = models.CharField(max_length=600)

    @property
    def rulings(self):
        tags = [self.name]
        return Ruling.objects.filter(tags__tag__in=tags)

    class Meta:
        ordering = ["name"]


class Trait(models.Model):

    def __str__(self):
        return self.name

    name = models.CharField(max_length=30)
    full = models.CharField(max_length=40)
    description = models.CharField(max_length=1300)

    @property
    def rulings(self):
        tags = [self.name]
        return Ruling.objects.filter(tags__tag__in=tags)

    class Meta:
        ordering = ["name"]


class Special(models.Model):
    def __str__(self):
        return self.name

    name = models.CharField(max_length=50)
    description = models.CharField(max_length=600)
    exceptional = models.BooleanField(default=False)

    objects = SpecialManager()


class UnitTrait(models.Model):

    def __str__(self):
        return self.unit.name + " - " + self.trait.name

    unit = models.ForeignKey(Unit, on_delete=models.CASCADE)
    trait = models.ForeignKey(Trait, on_delete=models.CASCADE)
    X = models.CharField(max_length=3, blank=True)
    Y = models.CharField(max_length=3, blank=True)
    descriptor = models.CharField(max_length=50, blank=True)

    @property
    def formatted(self):
        extra = self.trait.full.split(self.trait.name)[1]
        text = self.trait.name + extra\
            .replace("X", self.X)\
            .replace("Y", self.Y)\
            .replace("Descriptor", self.descriptor)\
            .replace("Bonus", self.descriptor)
        if "Descriptor" not in extra and "Bonus" not in extra and self.descriptor != "":
            text += f" [{self.descriptor}]"
        return text

    def save(self, *args, **kwargs):
        if "X" in self.trait.full and self.X == "":
            self.X = "1"
        if "Y" in self.trait.full and self.Y == "":
            self.Y = "1"
        super().save(*args, **kwargs)

    class Meta:
        ordering = ["trait__name"]


class UnitType(models.Model):

    def __str__(self):
        return self.unit.name + " - " + self.type

    unit = models.ForeignKey(Unit, related_name="types", on_delete=models.CASCADE)
    type = models.CharField(max_length=30)

    class Meta:
        ordering = ["type"]


class Event(models.Model):
    def __str__(self):
        return self.name
    name = models.CharField(max_length=50, default="")
    cycle = models.CharField(max_length=30, choices=CycleChoices, blank=True)
    cost = models.CharField(max_length=5, default="0")
    max = models.CharField(max_length=100, default="1", blank=True)
    # faction = models.CharField(max_length=15, default="")
    faction = models.ForeignKey(Faction, on_delete=models.CASCADE)
    description = models.CharField(max_length=2000, default="")
    restriction = models.CharField(max_length=300, blank=True)


class Theme(models.Model):
    def __str__(self):
        return self.faction.name + " - " + self.name
    name = models.CharField(max_length=40, default="")
    cycle = models.CharField(max_length=30, choices=CycleChoices, blank=True)
    # faction = models.CharField(max_length=15, default="")
    faction = models.ForeignKey(Faction, on_delete=models.CASCADE)
    validation = models.CharField(max_length=500, blank=True)
    description = models.CharField(max_length=1000, default="No description")
    restriction = models.CharField(max_length=300, blank=True)

    @property
    def permitted_units(self):
        permitted = Unit.objects.all()
        properties = get_properties(self)
        for filter_string in properties["FILTER"]:
            permitted = permitted.filter(q_object_from_string(filter_string))
        permitted |= Unit.objects.filter(properties__contains="ANYTHEME " + self.faction.shortName)
        # TODO models that can go in any theme that allows x model (eg niseru)
        for filter_string in properties["EXCLUDE"]:
            permitted = permitted.exclude(q_object_from_string(filter_string))
        permitted = permitted.exclude(Q(properties__contains="ONLYTHEME") & ~Q(properties__contains="ONLYTHEME " + self.name))
        return permitted.distinct()

    def save(self, *args, **kwargs):
        if len(self.validation) == 0 and len(self.restriction) != 0:
            permitted = re.search(r"Permitted \[(.*)\]", self.restriction)
            exclusion = re.search(r"Exclusion \[(.*)\]", self.restriction)
            if exclusion:
                exclusionList = exclusion.group(1).split(", ")
            if permitted:
                permittedList = permitted.group(1).split(", ")
            if permitted:
                result = "faction__shortName=\"" + self.faction.shortName + "\" AND types__type__in=["
                ronin = []
                for item in permittedList:
                    if item.find("Ronin") == -1:
                        result += "\"" + item + "\", "
                    else:

bushido/templates/bushido/detail_views/faction_details.html
{% extends "bushido/base.html" %}
{% load static %}
{% block title %}<title>{{faction.name}} - Info</title>{% endblock %}
{% block metatags %}
    <meta property="og:title" content="{{faction.name}} - Faction">
    <meta property="og:description" content="View information about {{faction.name}}, including models, themes and more">
{% endblock %}
{% block content %}
<div class="container m-0">
    <div>
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'bushido:index' %}">Home</a></li>
        <li class="breadcrumb-item"><a href="{% url 'bushido:allFactions' %}">Factions</a></li>
        <li class="breadcrumb-item active" aria-current="page">Faction</a></li>
      </ol>
    </nav>
  </div>
    <div class="row">
        <h2>{{faction.name}}</h2>
    </div>
  <hr>
    <div class="row">
<p>{{faction.description|linebreaks}}</p>
    </div>
  <hr>
    <div class="row">
<h4>Faction models:</h4>
<ul class="list-group">
    {% for unit in faction.unit_set.all %}
    <a class="list-group-item list-group-item-action" href="{% url 'bushido:modelDetails' unitid=unit.id%}">{{ unit.name }}</a>
        {% endfor %}
</ul>
    </div>
    <hr>
    <div class="row">
<h4>Faction Themes:</h4>
<ul class="list-group">
{% for theme in faction.theme_set.all %}
<a class="list-group-item list-group-item-action" href="{% url 'bushido:themeDetails' themeid=theme.id%}">{{ theme.name }}</a>
    {% endfor %}
    </ul>
    </div>
    <hr>
    <div class="row">
<h4>Faction Events:</h4>
<ul class="list-group">
{% for event in faction.event_set.all %}
<a class="list-group-item list-group-item-action" href="{% url 'bushido:eventDetails' eventid=event.id%}">{{ event.name }}</a>
    {% endfor %}
        </ul>
    </div>
  <hr>
      <div class="row">
<h4>Faction Enhancements:</h4>
<ul class="list-group">
  {% for enhancement in faction.enhancement_set.all %}
  {% if not enhancement.isEquipment %}
<a class="list-group-item list-group-item-action" href="{% url 'bushido:enhancementDetails' enhancementid=enhancement.id%}">{{ enhancement.name }}</a>
   {% endif %}
    {% endfor %}
        </ul>
    </div>
  <hr>
      <div class="row">
<h4>Faction Equipment:</h4>
<ul class="list-group">
  {% for enhancement in faction.enhancement_set.all %}
  {% if enhancement.isEquipment %}
<a class="list-group-item list-group-item-action" href="{% url 'bushido:enhancementDetails' enhancementid=enhancement.id%}">{{ enhancement.name }}</a>
  {% endif %}
    {% endfor %}
        </ul>
    </div>
  {% if faction.name != "Ronin" %}
  <hr>
      <div>

<h4>Ronin models:</h4>
<ul class="list-group">
    {% for unit in faction.ronin_units.all %}
    <a class="list-group-item list-group-item-action" href="{% url 'bushido:modelDetails' unitid=unit.id%}">{{ unit.name }}</a>
        {% endfor %}
</ul>
    </div>
  {% endif %}
</div>
{% endblock %}

bushido/templates/bushido/detail_views/unit_details.html
{% extends "bushido/base.html" %}
{% load static %}
{% load bushidofilters %}
{% block title %}<title>{{unit.name}} - Info</title>{% endblock %}
{% block metatags %}
    <meta property="og:title" content="{{unit.cardName}} - {{unit.faction.name}}">
    <meta property="og:image" content="{% static cardFront %}">
    <meta name="twitter:card" content="summary_large_image">
{% endblock %}
{% block content %}
<div class="container m-0">
  <div>
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'bushido:index' %}">Home</a></li>
        <li class="breadcrumb-item"><a href="{% url 'bushido:allFactions' %}">Factions</a></li>
        <li class="breadcrumb-item"><a href="{% url 'bushido:factionDetails' factionid=unit.faction.id%}">{{unit.faction.name}}</a></li>
        <li class="breadcrumb-item active" aria-current="page">Model</li>
      </ol>
    </nav>
  </div>
  <div>
    <h1>{{unit.cardName}}</h1>
    <p class="fw-light">{{unit.faction.name}}</p>
    <ul class="list-group list-group-horizontal">
      {% for type in unit.types.all %}
      {% if type.type not in unit.name and type.type not in unit.cardName %}
      <li class="list-group-item py-1">{{ type.type }}</li>
      {% endif %}
      {% endfor %}
    </ul>
  </div>
  <hr>
  <div class="container card-container">
    <div class="row gx-0">
      <div class="col-lg-6"><img src="{% static cardFront %}" class="img-fluid d-block" alt = "{{unit.cardName}} Front"></div>
      <div class="col-lg-6"><img src="{% static cardBack %}" class="img-fluid d-block" alt = "{{unit.cardName}} Back"></div>
    </div>
    {% if not user.userprofile.hide_unofficial_card_message %}
    {% if "/unofficial/" in cardFront or "/unofficial/" in cardBack %}
    <div class="row mt-1 text-center">
      <div class="col-lg-6">{% if "/unofficial/" in cardFront %}<p class="fw-light">Unofficial Card</p>{% endif %}</div>
      <div class="col-lg-6">{% if "/unofficial/" in cardBack %}<p class="fw-light">Unofficial Card</p>{% endif %}</div>
    </div>
    {% endif %}
    {% endif %}
  </div>
  <hr>
  {% if cardUnits|length != 1 %}
  <div class="mb-2">
    <p>This card represents multiple different models, each with their own abilities. Unless specified, a Warband may not recruit multiples of the same model.</p>
    <ul class="nav nav-tabs">
      {% for cardUnit in cardUnits %}
      <li class="nav-item">
        <a class="nav-link{% if cardUnit == unit %} active" aria-current="page{% endif %}" href="{% url 'bushido:modelDetails' unitid=cardUnit.id%}">{{cardUnit.name}}</a>
      </li>
      {% endfor %}
    </ul>
  </div>
  {% endif %}
  <div>
    <h4>Stats:</h4>
    <ul class="list-group list-group-horizontal text-center d-flex flex-wrap">
      <li class="list-group-item d-flex flex-fill justify-content-center">
        <div class="mx-2">
          <div class="fw-bold">Melee</div><hr class="py-0 my-1">
          {{unit.meleePool}} <span class="badge border border-light rounded-circle text-bg-dark">{{unit.meleeBoost}}</span>
        </div>
      </li>
      <li class="list-group-item d-flex flex-fill justify-content-center">
        <div class="mx-2">
          <div class="fw-bold">Ranged</div><hr class="py-0 my-1">
          {{unit.rangedPool}} <span class="badge border border-light rounded-circle text-bg-dark">{{unit.rangedBoost}}</span>
        </div>
      </li>
      <li class="list-group-item d-flex flex-fill justify-content-center">
        <div class="mx-2">
          <div class="fw-bold">Move</div><hr class="py-0 my-1">
          {{unit.movePool}} <span class="badge border border-light rounded-circle text-bg-dark">{{unit.moveBoost}}</span>
        </div>
      </li>
      <li class="list-group-item d-flex flex-fill justify-content-center">
        <div class="mx-2">
          <div class="fw-bold">Ki</div><hr class="py-0 my-1">
          {{unit.kiStat}}/{{unit.kiMax}} <span class="badge border border-light rounded-circle text-bg-dark">{{unit.kiBoost}}</span>
        </div>
      </li>
      <li class="list-group-item d-flex flex-fill justify-content-center">
        <div class="mx-2">
          <div class="fw-bold">Wounds</div><hr class="py-0 my-1">
          {{unit.wounds}}
        </div>
      </li>
      <li class="list-group-item d-flex flex-fill justify-content-center">
        <div class="mx-2">
          <div class="fw-bold">Cost</div><hr class="py-0 my-1">
          {{unit.cost}}
        </div>
      </li>
      <li class="list-group-item d-flex flex-fill justify-content-center">
        <div class="mx-2">
          <div class="fw-bold">Size</div><hr class="py-0 my-1">
          {{unit.size}} {{unit.baseSize}}mm
        </div>
      </li>
      <li class="list-group-item d-flex flex-fill justify-content-center">
        {% if unit.unique %}
        <div class="mx-0 d-flex align-items-center">
          <div class="fw-bold">Unique</div>
        </div>
          {% else %}
        <div class="mx-2">
          <div class="fw-bold">Max</div><hr class="py-0 my-1">
          {{unit.max}}
        </div>
        {% endif %}
      </li>
    </ul>
  </div>
  <hr>
  <h4>Weapons:</h4>
  <div class="container">
    <div class="row">
      {% for weapon in unit.weapons.all %}
      <div class="col-md-6 col-lg-4 gy-2">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">{{weapon.name}}</h5>
            <h6 class="card-subtitle mb-2 text-muted">{{weapon.strength}} | {% if weapon.isRanged %}Ranged {{weapon.shortRange}}/{{weapon.mediumRange}}/{{weapon.longRange}}{% else %}Melee{% endif %}</h6>
            <ul class="list-group list-group-flush">
              {% for trait in weapon.weapontraits.all %}
              <a class="list-group-item list-group-item-action" href="{% url 'bushido:allTraits' %}#{{trait.trait.name}}">{{ trait.formatted }}</a>
              {% endfor %}
              {% for special in weapon.weaponspecials.all %}
              <a class="list-group-item list-group-item-action" href="{% url 'bushido:allSpecials' %}#{{special.special.name}}">{{special.special.name}} ({{special.cost}})</a>
              <!--li class="list-group-item">{{special.special.name}} ({{special.cost}})</li-->
              {% endfor %}
            </ul>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
  <hr>
  <div>
    <h4>Traits:</h4>
    {% if unit.unittrait_set.all|length == 0 %}
    <p>None</p>
    {% else %}
    <ul class="list-group list-group-horizontal-md d-flex flex-wrap">
      {% for trait in unit.unittrait_set.all %}
      <a class="list-group-item list-group-item-action w-auto py-md-2" href="{% url 'bushido:allTraits' %}#{{trait.trait.name}}">{{ trait.formatted }}</a>
      {% endfor %}
    </ul>
    {% endif %}
  </div>
  <hr>
  <div>
    <h4>Feats:</h4>
    {% if unit.kiFeats.all|length == 0 %}
    <p>None</p>
    <hr>
    {% else %}
    <table class="table">
      <thead class="table-group-divider">
      <tr>
        <th>Name</th>
        <th>Cost</th>
        <th>Timing</th>
        <th>Type</th>
      </tr>
      </thead>
      <tbody>
      {% for feat in unit.kiFeats.all %}
      <tr>
        <td><a href="{% url 'bushido:featDetails' featid=feat.id%}">{{ feat.name }}</a></td>
        <td>{{ feat.cost }}</td>
        <td>{{ feat.timing }}</td>
        <td>{{ feat.featType }}</td>
      </tr>
      {% endfor %}
      </tbody>
    </table>
    {% endif %}
  </div>
  <div>
    <h4>Unique Effects:</h4>
    {% if unit.uniqueEffects == "" %}
    <p>None</p>
    {% else %}
    <p>{{ unit.uniqueEffects|linebreaks }}</p>
    {% endif %}
  </div>
    {% if unit.faction.name == "Ronin" %}
  <div>
    <h4>Permitted factions:</h4>
    <ul class="list-group">
      {% for faction in unit.ronin_factions.all %}
          <a class="list-group-item list-group-item-action" href="{% url 'bushido:factionDetails' factionid=faction.id %}">
              {{faction.name}}
          </a>
      {% endfor %}
      </ul>
  </div>
  {% endif %}
  <hr>
  <div>
    <h4>Rulings:</h4>
    <div class="list-group">
      {% for ruling in unit.rulings %}
      <div class="list-group-item w-auto py-md-2">
        <p>{{ ruling.ruling }}</p>
        <div class="d-flex">
          <small class="me-auto">
            {% for tag in ruling.tags.all %}
              {{ tag.tag }}{% if not forloop.last %}, {% endif %}
            {% endfor %}
          </small>
          <small>{{ ruling.date }}</small>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
  {% if perms.bushido.change_unit %}
  <hr>
  <a class="btn btn-outline-secondary" href="./edit/" role="button">Edit model</a>
  {% endif %}
</div>
{% endblock %}